### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused)

### ISSUE THREAD

**Issue by do-d1** [debricked/dmarc-visualizer#30]
Hi 

any quik fix for :
Failed to establish a new connection: [Errno 111] Connection refused)

what and where to change ? 

`docker-compose up
Creating network "dmarcvisualizer_default" with the default driver
Creating dmarcvisualizer_grafana_1 ...
Creating dmarcvisualizer_elasticsearch_1 ...
Creating dmarcvisualizer_elasticsearch_1
Creating dmarcvisualizer_grafana_1 ... done
Creating dmarcvisualizer_parsedmarc_1 ...
Creating dmarcvisualizer_parsedmarc_1 ... done
Attaching to dmarcvisualizer_elasticsearch_1, dmarcvisualizer_grafana_1, dmarcvisualizer_parsedmarc_1
grafana_1        | ✔ Downloaded grafana-piechart-panel v1.6.2 zip successfully
grafana_1        |
grafana_1        | Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
grafana_1        |
parsedmarc_1     | Traceback (most recent call last):
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
parsedmarc_1     |     conn = connection.create_connection(
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
parsedmarc_1     |     raise err
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
parsedmarc_1     |     sock.connect(sa)
parsedmarc_1     | ConnectionRefusedError: [Errno 111] Connection refused
parsedmarc_1     |
parsedmarc_1     | During handling of the above exception, another exception occurred:
parsedmarc_1     |
parsedmarc_1     | Traceback (most recent call last):
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py", line 255, in perform_request
parsedmarc_1     |     response = self.pool.urlopen(
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
parsedmarc_1     |     retries = retries.increment(
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 525, in increment
parsedmarc_1     |     raise six.reraise(type(error), error, _stacktrace)
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
parsedmarc_1     |     raise value
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
parsedmarc_1     |     httplib_response = self._make_request(
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
parsedmarc_1     |     conn.request(method, url, **httplib_request_kw)
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
parsedmarc_1     |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
parsedmarc_1     |   File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
parsedmarc_1     |     self._send_request(method, url, body, headers, encode_chunked)
parsedmarc_1     |   File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
parsedmarc_1     |     self.endheaders(body, encode_chunked=encode_chunked)
parsedmarc_1     |   File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
parsedmarc_1     |     self._send_output(message_body, encode_chunked=encode_chunked)
parsedmarc_1     |   File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
parsedmarc_1     |     self.send(msg)
parsedmarc_1     |   File "/usr/local/lib/python3.10/http/client.py", line 975, in send
parsedmarc_1     |     self.connect()
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
parsedmarc_1     |     conn = self._new_conn()
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
parsedmarc_1     |     raise NewConnectionError(
parsedmarc_1     | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f646bdfc8b0>: Failed to establish a new connection: [Errno 111] Connection refused
parsedmarc_1     |
parsedmarc_1     | During handling of the above exception, another exception occurred:
parsedmarc_1     |
parsedmarc_1     | Traceback (most recent call last):
parsedmarc_1     |   File "/usr/local/bin/parsedmarc", line 8, in <module>
parsedmarc_1     |     sys.exit(_main())
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/parsedmarc/cli.py", line 684, in _main
parsedmarc_1     |     elastic.migrate_indexes(aggregate_indexes=[es_aggregate_index],
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/parsedmarc/elastic.py", line 244, in migrate_indexes
parsedmarc_1     |     if not Index(aggregate_index_name).exists():
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch_dsl/index.py", line 414, in exists
parsedmarc_1     |     return self._get_connection(using).indices.exists(index=self._name, **kwargs)
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/client/utils.py", line 347, in _wrapped
parsedmarc_1     |     return func(*args, params=params, headers=headers, **kwargs)
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/client/indices.py", line 371, in exists
parsedmarc_1     |     return self.transport.perform_request(
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/transport.py", line 417, in perform_request
parsedmarc_1     |     self._do_verify_elasticsearch(headers=headers, timeout=timeout)
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/transport.py", line 606, in _do_verify_elasticsearch
parsedmarc_1     |     raise error
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/transport.py", line 569, in _do_verify_elasticsearch
parsedmarc_1     |     _, info_headers, info_response = conn.perform_request(
parsedmarc_1     |   File "/usr/local/lib/python3.10/site-packages/elasticsearch/connection/http_urllib3.py", line 280, in perform_request
parsedmarc_1     |     raise ConnectionError("N/A", str(e), e)
parsedmarc_1     | elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7f646bdfc8b0>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f646bdfc8b0>: Failed to establish a new connection: [Errno 111] Connection refused)
`

**Comment by sushantrimal10** [comment]
Hi, Did you find any solution to resolve this issue? I am having the same issue.

**Comment by neomathews** [comment]
Hi, i'm stuck here too. Anyone?

**Comment by supaeasy** [comment]
Did you try waiting for 15 minutes?

**Comment by do-d1** [comment]
actually i assembled new working project that i collect like a puzzle from other projects.
i will upload it soon and will post a link.

**Comment by rohinihirurkar** [comment]
Please share the link

**Comment by WillowMist** [comment]
Seconded.  Same issue.

**Comment by rtlong** [comment]
For anyone still struggling with this, see my comment on this newer Issue https://github.com/debricked/dmarc-visualizer/issues/41#issuecomment-1386567305
